# assembly generated by minc compiler ...
	.globl	f
    .type	f, @function
f:
    .cfi_startproc
    pushq	%rbp
    movq	%rsp, %rbp
	subq	$0, %rsp
	subq	$0, %rsp
	pushq	$123
	popq	%rax
	leave
	ret
	.cfi_endproc
