# assembly generated by minc compiler ...
	.globl	f
    .type	f, @function
f:
    .cfi_startproc
    pushq	%rbp
    movq	%rsp, %rbp
	movq	%rdi, -8(%rbp)
	movq	%rsi, -16(%rbp)
	movq	%rdx, -24(%rbp)
	subq	$24, %rsp
	subq	$0, %rsp
	movq	-8(%rbp), %rax
	pushq	%rax
	popq	%rax
	cmp	$0, %rax
	je	ELSE_0
	subq	$0, %rsp
	movq	-16(%rbp), %rax
	pushq	%rax
	movq	-24(%rbp), %rax
	pushq	%rax
	popq	%rax
	popq	%rcx
	addq	%rax, %rcx
	pushq	%rcx
	popq	%rax
	leave
	ret
	jmp	IF_END_0
ELSE_0:
	subq	$0, %rsp
	movq	-16(%rbp), %rax
	pushq	%rax
	movq	-24(%rbp), %rax
	pushq	%rax
	popq	%rax
	popq	%rcx
	imulq	%rcx
	pushq	%rax
	popq	%rax
	leave
	ret
IF_END_0:
	.cfi_endproc
