# assembly generated by minc compiler ...
	.globl	f
    .type	f, @function
f:
    .cfi_startproc
    pushq	%rbp
    movq	%rsp, %rbp
	movq	%rdi, -8(%rbp)
	movq	%rsi, -16(%rbp)
	movq	%rdx, -24(%rbp)
	subq	$24, %rsp
	subq	$8, %rsp
	pushq	$100
	popq	%rax
	movq	%rax, -32(%rbp)
	movq	-8(%rbp), %rax
	pushq	%rax
	pushq	$0
	popq	%rax
	popq	%rcx
	cmpq	%rax, %rcx
	movq	$0, %rax
	setg	%al
	pushq	%rax
	popq	%rax
	cmp	$0, %rax
	jz	IF_END_0
	movq	-16(%rbp), %rax
	pushq	%rax
	pushq	$0
	popq	%rax
	popq	%rcx
	cmpq	%rax, %rcx
	movq	$0, %rax
	setg	%al
	pushq	%rax
	popq	%rax
	cmp	$0, %rax
	je	ELSE_1
	pushq	$200
	popq	%rax
	movq	%rax, -32(%rbp)
	jmp	IF_END_1
ELSE_1:
	pushq	$300
	popq	%rax
	movq	%rax, -32(%rbp)
IF_END_1:
IF_END_0:
	movq	-32(%rbp), %rax
	pushq	%rax
	popq	%rax
	leave
	ret
	.cfi_endproc
