# assembly generated by minc compiler ...
	.globl	f
    .type	f, @function
f:
    .cfi_startproc
    pushq	%rbp
    movq	%rsp, %rbp
	movq	%rdi, -8(%rbp)
	subq	$8, %rsp
	subq	$8, %rsp
	pushq	$2
	popq	%rax
	movq	%rax, -16(%rbp)
	jmp	WHILE_COND_0
WHILE_BODY_0:
	subq	$0, %rsp
	movq	-8(%rbp), %rax
	pushq	%rax
	movq	-16(%rbp), %rax
	pushq	%rax
	movq	$0, %rdx
	popq	%rcx
	popq	%rax
	idivq	%rcx
	pushq	%rdx
	pushq	$0
	popq	%rcx
	popq	%rax
	cmpq	%rax, %rcx
	movq	$0, %rax
	sete	%al
	pushq	%rax
	popq	%rax
	cmp	$0, %rax
	jz	IF_END_0
	pushq	$0
	popq	%rax
	leave
	ret
IF_END_0:
	movq	-16(%rbp), %rax
	pushq	%rax
	pushq	$1
	popq	%rax
	popq	%rcx
	addq	%rax, %rcx
	pushq	%rcx
	popq	%rax
	movq	%rax, -16(%rbp)
WHILE_COND_0:
	movq	-16(%rbp), %rax
	pushq	%rax
	movq	-16(%rbp), %rax
	pushq	%rax
	popq	%rax
	popq	%rcx
	imulq	%rcx
	pushq	%rax
	movq	-8(%rbp), %rax
	pushq	%rax
	popq	%rax
	popq	%rcx
	cmpq	%rax, %rcx
	movq	$0, %rax
	setle	%al
	pushq	%rax
	popq	%rax
	cmpq	$0, %rax
	jne	WHILE_BODY_0
WHILE_END_0:
	pushq	$1
	popq	%rax
	leave
	ret
	.cfi_endproc
