# assembly generated by minc compiler ...
	.globl	f
    .type	f, @function
f:
    .cfi_startproc
    endbr64
    pushq	%rbp
    movq	%rsp, %rbp
	movq	%rdi, -8(%rbp)
	subq	$8, %rsp
	movq	-8(%rbp), %rsi
	pushq	%rsi
	popq	%rax
	negq	%rax
	pushq	%rax
	popq	%rax
	leave
	ret
	.cfi_endproc
