# assembly generated by minc compiler ...
	.globl	f
    .type	f, @function
f:
    .cfi_startproc
    endbr64
    pushq	%rbp
    movq	%rsp, %rbp
	movq	%rdi, -8(%rbp)
	.ERR_not_implemented_op
	popq	%rax
	leave
	ret
	.cfi_endproc
