# assembly generated by minc compiler ...
	.globl	f
    .type	f, @function
f:
    .cfi_startproc
    endbr64
    pushq	%rbp
    movq	%rsp, %rbp
	movq	%rdi, -8(%rbp)
	subq	$8, %rsp
	pushq	$2
	popq	%rax
	movq	%rax, 16(%rbp)
	pushq	%rax
	pushq	$1
	popq	%rax
	leave
	ret
	.cfi_endproc
