# assembly generated by minc compiler ...
	.globl	f01
    .type	f01, @function
f01:
    .cfi_startproc
    endbr64
    pushq	%rbp
    movq	%rsp, %rbp
	subq	$0, %rsp
	pushq	$10
	popq	%rax
	negq	%rax
	pushq	%rax
	popq	%rax
	leave
	ret
	.cfi_endproc
	.globl	f
    .type	f, @function
f:
    .cfi_startproc
    endbr64
    pushq	%rbp
    movq	%rsp, %rbp
	movq	%rdi, -8(%rbp)
	subq	$8, %rsp
	subq	$16, %rsp
	call	f01
	addq	$16, %rsp
	movq	%rax, 16(%rsp)
	pushq	$1
	popq	%rax
	popq	%rcx
	addq	%rax, %rcx
	pushq	%rcx
	popq	%rax
	leave
	ret
	.cfi_endproc
